[profile.default]
src = "src"
out = "out"
test = "test"
script = "scripts"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]
no_match_path = "lib/**"

[profile.ci]
verbosity = 4
fuzz = { runs = 1024 }
invariant = { runs = 256, depth = 50 }

[rpc_endpoints]
hyperevm = "${HYPEREVM_RPC}"
testnet = "${HYPEREVM_TESTNET_RPC}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
